/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#7a877f",
        "tertiary": "#000000",
        "on-error": "#ffffff",
        "surface-container-high": "#e6e8ea",
        "surface-variant": "#e0e3e5",
        "on-primary-container": "#7c839b",
        "surface-bright": "#f7f9fb",
        "on-secondary-container": "#006f66",
        "primary": "#000000",
        "surface-container": "#eceef0",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#2d3133",
        "inverse-primary": "#bec6e0",
        "on-secondary-fixed-variant": "#005049",
        "on-primary-fixed-variant": "#3f465c",
        "error": "#ba1a1a",
        "outline": "#76777d",
        "primary-container": "#131b2e",
        "secondary-container": "#86f2e4",
        "tertiary-fixed": "#d9e6dd",
        "secondary-fixed": "#89f5e7",
        "on-secondary": "#ffffff",
        "surface-dim": "#d8dadc",
        "on-primary-fixed": "#131b2e",
        "surface-container-low": "#f2f4f6",
        "secondary": "#006a61",
        "surface-tint": "#565e74",
        "on-tertiary-fixed-variant": "#3e4943",
        "on-tertiary": "#ffffff",
        "background": "#f7f9fb",
        "error-container": "#ffdad6",
        "primary-fixed-dim": "#bec6e0",
        "surface-container-highest": "#e0e3e5",
        "on-error-container": "#93000a",
        "on-surface-variant": "#45464d",
        "secondary-fixed-dim": "#6bd8cb",
        "tertiary-container": "#131e19",
        "tertiary-fixed-dim": "#bdcac1",
        "surface": "#f7f9fb",
        "on-tertiary-fixed": "#131e19",
        "on-surface": "#191c1e",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#eff1f3",
        "outline-variant": "#c6c6cd",
        "on-background": "#191c1e",
        "primary-fixed": "#dae2fd",
        "on-secondary-fixed": "#00201d",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "4xl": "2.5rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "16px",
        "stack-sm": "8px",
        "stack-md": "24px",
        gutter: "24px",
        "container-max": "1280px",
        "margin-desktop": "40px",
        "stack-lg": "48px",
        "section-lg": "120px",
        unit: "4px",
      },
      fontFamily: {
        "body-md": ["Manrope"],
        "label-sm": ["Manrope"],
        "label-md": ["Manrope"],
        "headline-sm": ["Plus Jakarta Sans"],
        "body-lg": ["Manrope"],
        "headline-md": ["Plus Jakarta Sans"],
        "display-lg": ["Plus Jakarta Sans"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "1.4", letterSpacing: "0.05em", fontWeight: "500" }],
        "label-md": ["14px", { lineHeight: "1.4", letterSpacing: "0.02em", fontWeight: "600" }],
        "headline-sm": ["24px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.7", letterSpacing: "0", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
      boxShadow: {
        premium: "0 20px 50px rgba(0, 0, 0, 0.05)",
        "card-hover": "0 30px 60px rgba(0, 106, 97, 0.12)",
      },
      maxWidth: {
        "container-max": "1280px",
      },
    },
  },
  plugins: [],
};
