/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#7a8aaf",
        "tertiary": "#1a237e",
        "on-error": "#ffffff",
        "surface-container-high": "#e4e7f0",
        "surface-variant": "#dde1ee",
        "on-primary-container": "#7c87b0",
        "surface-bright": "#f5f7fc",
        "on-secondary-container": "#1a237e",
        "primary": "#1a237e",
        "surface-container": "#eaecf5",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#1e2340",
        "inverse-primary": "#b0b8d8",
        "on-secondary-fixed-variant": "#1a237e",
        "on-primary-fixed-variant": "#2d3561",
        "error": "#ba1a1a",
        "outline": "#6b6f85",
        "primary-container": "#1a237e",
        "secondary-container": "#c5cae9",
        "tertiary-fixed": "#d5d9ee",
        "secondary-fixed": "#c5cae9",
        "on-secondary": "#ffffff",
        "surface-dim": "#d5d8e8",
        "on-primary-fixed": "#1a237e",
        "surface-container-low": "#eef0f8",
        "secondary": "#1a237e",
        "surface-tint": "#3949ab",
        "on-tertiary-fixed-variant": "#2d3561",
        "on-tertiary": "#ffffff",
        "background": "#f5f7fc",
        "error-container": "#ffdad6",
        "primary-fixed-dim": "#b0b8d8",
        "surface-container-highest": "#dde1ee",
        "on-error-container": "#93000a",
        "on-surface-variant": "#44475a",
        "secondary-fixed-dim": "#9fa8da",
        "tertiary-container": "#1a237e",
        "tertiary-fixed-dim": "#b0b8d8",
        "surface": "#f5f7fc",
        "on-tertiary-fixed": "#1a237e",
        "on-surface": "#1a1c2e",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#eef0f8",
        "outline-variant": "#c2c5d6",
        "on-background": "#1a1c2e",
        "primary-fixed": "#dde1f5",
        "on-secondary-fixed": "#0d1257",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "4xl": "2.5rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "16px",
        "stack-sm": "8px",
        "stack-md": "24px",
        gutter: "24px",
        "container-max": "1280px",
        "margin-desktop": "40px",
        "stack-lg": "48px",
        "section-lg": "120px",
        unit: "4px",
      },
      fontFamily: {
        "body-md": ["Manrope"],
        "label-sm": ["Manrope"],
        "label-md": ["Manrope"],
        "headline-sm": ["Plus Jakarta Sans"],
        "body-lg": ["Manrope"],
        "headline-md": ["Plus Jakarta Sans"],
        "display-lg": ["Plus Jakarta Sans"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "1.4", letterSpacing: "0.05em", fontWeight: "500" }],
        "label-md": ["14px", { lineHeight: "1.4", letterSpacing: "0.02em", fontWeight: "600" }],
        "headline-sm": ["24px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.7", letterSpacing: "0", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
      boxShadow: {
        premium: "0 20px 50px rgba(0, 0, 0, 0.05)",
        "card-hover": "0 30px 60px rgba(26, 35, 126, 0.12)",
      },
      maxWidth: {
        "container-max": "1280px",
      },
    },
  },
  plugins: [],
};
